name: flutter_web_notification_platform
description: A Flutter plugin for web notifications using conditional imports.
version: 1.0.2
homepage: https://github.com/bagusandrewijaya/flutter_web_notification_platform
repository: https://github.com/bagusandrewijaya/flutter_web_notification_platform

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
