name: flutter_web_notification_platform
description: A Flutter plugin for web notifications using conditional imports.
version: 1.0.0
homepage: https://github.com/your-repo/flutter_web_notification_platform
repository: https://github.com/your-repo/flutter_web_notification_platform

flutter:
  plugin:
    platforms:
      web:
        pluginClass: PlatformNotificationWeb
        fileName: lib/src/platform_notification_web.dart

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
